name: Weekly ESPN Pull
on:
  schedule:
    - cron: "0 11 * * 2"   # Tuesdays 7:00 AM America/Detroit (ET)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt

      # ✅ Check ENV (since LEAGUE_ID is hard-coded below in the same step)
      - name: Pull ESPN data
        run: |
          test -n "${LEAGUE_ID}" || (echo "LEAGUE_ID env is empty" && exit 1)
          test -n "${YEAR}" || (echo "YEAR env is empty" && exit 1)
          python pull.py
        env:
          LEAGUE_ID: ${{ secrets.LEAGUE_ID }}   # <- your league id (keep as string)
          YEAR: ${{ secrets.YEAR }}             # or "2025"
          ESPN_S2: ${{ secrets.ESPN_S2 }}       # omit if public
          SWID: ${{ secrets.SWID }}             # omit if public

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: out/

      - name: Commit artifacts
        run: |
          git config user.name "espn-bot"
          git config user.email "espn-bot@users.noreply.github.com"
          git add out/ || true
          git commit -m "Auto: week update" || echo "No changes to commit"
          git push || echo "Push failed (likely no changes or permissions)"

